repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
        exclude: packaging/.*
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=setup.cfg]

  - repo: https://github.com/omnilib/ufmt
    rev: v1.3.1
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 21.9b0
          - usort == 0.6.4

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.13
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
          - mdformat_frontmatter
