# See https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

enabled: false

pull_requests: true

commit_template: |
  [skip ci] Restyled by ${restyler.name}

exclude:
  - "**/*.patch"

statuses:
  differences: true
  no_differences: true
  error: true

restylers:
  - clang-format
